#
# Team 43, Melbourne
# Aidan McLoughney(1030836)
# Thanaboon Muangwong(1049393)
# Nahid Tajik(1102790)
# Saket Khandelwal (1041999)
# Shmuli Bloom(982837)
#

---
- name: Load Couchdb Image
  become: yes
  docker_image:
    name: ibmcom/couchdb3:3.0.0
    source: pull

- name: start Couchdb container
  become: yes
  docker_container:
    name: couchdb
    image: ibmcom/couchdb3:3.0.0
    state: started
    volumes: /data/couchdb/data:/opt/couchdb/data
    restart_policy: on-failure
    ports:
      - "5984:5984"
      - "4369:4369" 
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: '{{ couchdb_user }}'
      COUCHDB_PASSWORD: '{{ couchdb_password }}'
      COUCHDB_SECRET: '{{ couchdb_secret }}'
      ERL_FLAGS: "-setcookie \"{{ couchdb_secret }}\" -name \"couchdb@{{ ansible_default_ipv4.address }}\""

