#
# Team 43, Melbourne
# Aidan McLoughney(1030836)
# Thanaboon Muangwong(1049393)
# Nahid Tajik(1102790)
# Saket Khandelwal (1041999)
# Shmuli Bloom(982837)
#

# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: jam-vol-4-1
    vol_size: 10
  - vol_name: jam-vol-4-2
    vol_size: 25

# Volume Snapshots for the Couch-DB volumes
snapshot_volumes:
  - vol_name: jam-vol-4-2
    vol_size: 25


# Security group
security_groups:
  - name: jam_ssh
    description: "Jam security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: jam_http
    description: "jam security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: "security group for CouchDB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: "security group for CouchDB"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_group
    description: "security group for CouchDB"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: jam-4
    volumes: ['jam-vol-4-1', 'jam-vol-4-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: amclo
instance_flavor: uom.mse.2c9g
jam_groups: ['Cuatro']