---
- name: Load Twitter Docker Files
  synchronize: src=harvester_files dest=/tmp

- name: Add Python Twitter Config
  become: yes
  lineinfile:
    path: /tmp/harvester_files/Dockerfile
    insertafter: FROM python:3
    line: ENV CONFIG_FILE {{ py_twitter_config }}

- name: Add Couchdb URL to Config
  become: yes
  lineinfile:
    path: /tmp/harvester_files/config/{{ py_twitter_config }}
    insertafter: "['couch']" 
    line: URL = http://{{ couchdb_user }}:{{ couchdb_password }}@{{ ansible_default_ipv4.address }}:{{ couchdb_port }}/

- name: Build image and with build args
  become: yes
  docker_image:
    name: twitter_docker
    force_source: yes
    build:
      path: /tmp/harvester_files
      args:
        listen_port: 8080
    source: build
  register: image_build

- name: Start a container with a command
  become: yes
  docker_container:
    name: twitter_harvester
    image: twitter_docker
    restart_policy: on-failure
    volumes: ~/harvester_logs:/usr/src/app/tmp
  register: docker_output