#
# Team 43, Melbourne
# Aidan McLoughney(1030836)
# Thanaboon Muangwong(1049393)
# Nahid Tajik(1102790)
# Saket Khandelwal (1041999)
# Shmuli Bloom(982837)
#

---
# Create volume snapshot(s)
- name: Create volume snapshot(s)
  os_volume_snapshot:
    state: present
    volume: '{{ item.vol_name }}'
    display_name: "{{ item.vol_name }}-{{ lookup('pipe', 'date +%Y-%m-%d') }}"
    wait: yes
    timeout: 600
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ snapshot_volumes }}'