- name: Check connection
  args:
    warn: yes
  shell: 'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}" '
  register: connection_check

- name: Enable Cluster
  shell: 'curl -XPOST "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" --header "Content-Type: application/json" --data "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\", \"port\": \"{{ couchdb_port }}\", \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ couchdb_node_number }}\", \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_password }}\"}"'
  args:
    warn: yes
  loop: '{{ groups["Play"] }}'
  when: item != groups["Uno"].0

- name: Add Nodes to Cluster
  shell: 'curl -XPOST "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" --header "Content-Type: application/json"  --data "{\"action\": \"add_node\", \"host\":\"{{ item }}\", \"port\": \"{{ couchdb_port }}\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_password }}\"}"'
  args:
    warn: yes
  loop: '{{ groups["Play"] }}'
  when: item != groups["Uno"].0

- name: Finish cluster Setup
  args:
    warn: yes
  shell: 'curl -XPOST "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"'

- name: Verify installation
  args:
    warn: yes
  shell: 'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" '

- name: Verify connection of nodes
  args:
    warn: yes
  shell:  'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_membership" '

- name: Create Tweets Database 
  args:
    warn: yes
  shell: 'curl -X PUT "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/twt_db?q=8&n=3"'

- name: Create Users Database
  args:
    warn: yes
  shell: 'curl -X PUT "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/user_db?q=8&n=3"'

- name: Create CouchDB Views Directory
  become: yes
  file:
    path: /data/couchdbViews
    state: directory

- name: Copy view 
  become: yes
  copy:
    src: ./couchdb_files/grp43View.json
    dest: /data/couchdbViews

- name: create view in tweets database
  args:
    warn: yes
  shell: 'curl -X PUT http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/twt_db/_design/grp43 --data-binary @/data/couchdbViews/grp43View.json'