- name: Finish cluster Setup
  args:
    warn: yes
  shell: 'curl -XPOST "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" --header "Content-Type: application/json" --data "{\"action\": \"finish_cluster\"}"'

- name: Verify installation
  args:
    warn: yes
  shell: 'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_cluster_setup" '

- name: Verify connection of nodes
  args:
    warn: yes
  shell:  'curl "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/_membership" '

- name: Create Tweets Database 
  args:
    warn: yes
  shell: 'curl -X PUT "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/tweets_db?q=8&n=3"'

- name: Create Users Database
  args:
    warn: yes
  shell: 'curl -X PUT "http://{{ couchdb_user }}:{{ couchdb_password }}@{{ groups["Uno"].0 }}:{{ couchdb_port }}/users_db?q=8&n=3"'

- name: Create CouchDB Views Directory
  become: yes
  file:
    path: /data/couchdbViews
    state: directory

