#
# Team 43, Melbourne
# Aidan McLoughney(1030836)
# Thanaboon Muangwong(1049393)
# Nahid Tajik(1102790)
# Saket Khandelwal (1041999)
# Shmuli Bloom(982837)
#


---
# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk